//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drehevel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RuntimeMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RuntimeMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Drehevel.Properties.RuntimeMessages", typeof(RuntimeMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build aborted..
        /// </summary>
        internal static string BuildAborted {
            get {
                return ResourceManager.GetString("BuildAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build finished in {0:0.00}s!.
        /// </summary>
        internal static string BuildFinished {
            get {
                return ResourceManager.GetString("BuildFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Settings.
        /// </summary>
        internal static string BuildSettings {
            get {
                return ResourceManager.GetString("BuildSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please cancel the build before exiting the application..
        /// </summary>
        internal static string CancelBeforeQuitMessage {
            get {
                return ResourceManager.GetString("CancelBeforeQuitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build in progress!.
        /// </summary>
        internal static string CancelBeforeQuitTitle {
            get {
                return ResourceManager.GetString("CancelBeforeQuitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balanced.
        /// </summary>
        internal static string DefaultCompression {
            get {
                return ResourceManager.GetString("DefaultCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set both a project directory and an output file path..
        /// </summary>
        internal static string EmptyOptionsMessage {
            get {
                return ResourceManager.GetString("EmptyOptionsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Settings.
        /// </summary>
        internal static string EmptyOptionsTitle {
            get {
                return ResourceManager.GetString("EmptyOptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fastest.
        /// </summary>
        internal static string FastCompression {
            get {
                return ResourceManager.GetString("FastCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest.
        /// </summary>
        internal static string HighCompression {
            get {
                return ResourceManager.GetString("HighCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string NoCompression {
            get {
                return ResourceManager.GetString("NoCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing file {0}/{1} ({2}).
        /// </summary>
        internal static string ProcessingFile {
            get {
                return ResourceManager.GetString("ProcessingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip archive.
        /// </summary>
        internal static string ZipArchive {
            get {
                return ResourceManager.GetString("ZipArchive", resourceCulture);
            }
        }
    }
}
